### PR TITLE
Fixes #14 countdown not working on ProPresenter 6

### LINKED ISSUE #14: Countdown not working
Before posting this, I have been trying to figure out how to make it work but there are no comments to understand really the code (and I am not good with javascript, so the whole code is confusing to me). I tried to "parse" the countdown like this:

```
function parseCountdown(data) {
  if(data == "--:--:--" || data.indexOf(' ') >= 0) {
    data = "";
  }
  return data;
}
```

(I used console.log(data); in contentPreprocessors to get the data)

Right now the code just count backwards from 0:00:00 to -0:00:07 or so in a 1:00:00 countdown and then restarts. console.log(data) shows the real "content" of the data (0:59:59 then line break with --:--:-- and then 0:59:58 then line break with --:--:-- and so on, that's the why of the if in the function)

Can you comment a bit more the code or help me resolve this?

Also, I gave up in this point but the clock (in Pro6 Mac Stage Display) is displayed like 2016/11/19 11:57:42 p.m. but in the app, for some reason I have not figured out yet, only the hour is displayed in 24 hour format (I tried checking the functions in scripts.js but these were confusing so better not touch it for now)

Thanks for the help and this great tool!

### PR DESCRIPTION
**Pull request by jswetzen**
@kevindoveton what do you think about this solution? Code review and critique is appreciated :)

### CODE REVIEW

**Comment by kevindoveton** [comment]
makes sense to do as much as possible on the server :) all looks good to me, have you tested on pro6 or do you need me to?

**Comment by jswetzen** [comment]
I tested on pro5 only, but added two tests that should cover the new cases. If you have time it would be great if you could test it and check that the test cases do indeed cover the pro6 messages

**Comment by kevindoveton** [comment]
this almost works, it doesn't cover the negative countdown case. If the countdown goes below zero (overrun) it should show a negative value but it shows the positive version and then starts counting down from that. I think it should be a simple case of checking if `time[0]` is negative in the `parseTime` function?

**Comment by jswetzen** [comment]
I think it works now, at least it handles the test cases I added

**Comment by kevindoveton** [comment]
propresenter will sometimes send nulls to parsetime, you checked for that with the main bit of code but the `time[1]` bit was outside of the if statement, It needs to be inside. 

May also be worth adding a test case for null. 

    if (time !== null) {
        seconds += 3600 * ( (parseInt(time[2], 10)) + (time[6] ? 12 : 0) );
        seconds += 60 * ( parseInt(time[3], 10) || 0 );
        seconds += ( parseInt(time[5], 10) || 0 );

        if (time[1] !== undefined) {
          seconds *= -1;
        }
    }

**Comment by jswetzen** [comment]
I completely missed that, fixed now!

**Comment by kevindoveton** [comment]
Works perfectly in Pro5, Pro6 doesn't stop unless another timer is also running - but i'm not sure if that problem has been around forever.

**Comment by kevindoveton** [comment]
Actually it does work in Pro6, just can take up to 30 seconds to update. I think it's safe to merge :)

**Comment by jswetzen** [comment]
Are you running ProPresenter on Windows? The client-side updates were added because Windows was sending clock updates every minute or so while Mac did it every second, and I wanted it to keep ticking always. I think it keeps going because ProPresenter hasn't sent anything, because ProPresenter sends a "running" property that's removed when it's stopped. So I think it's safe to merge too :)

**Comment by kevindoveton** [comment]
I'm running on mac, but in pro6 as you said it just stopped sending anything when the countdown stopped

**Comment by jswetzen** [comment]
Hmm, interesting choice. It would have been nice to at least get one update to know that it stopped! But there's nothing to do about it.

**Pull request merged**
